"""Generate self-hosted, disjoint Unicode shards. Requires fonttools[woff].

Run manually when replacing source fonts; all glyphs remain covered, so adding
articles does not require regeneration. Original fonts and OFL files are kept.
"""
from collections import Counter
from pathlib import Path
import hashlib
from fontTools.ttLib import TTFont
from fontTools import subset

ROOT = Path(__file__).resolve().parents[1]
FONTS = ROOT / 'docs/public/fonts'
OUT = FONTS / 'web'
OUT.mkdir(exist_ok=True)
counts = Counter()
for path in (ROOT / 'docs').rglob('*.md'):
    if '.vitepress' not in path.parts and 'public' not in path.parts:
        counts.update(map(ord, path.read_text(encoding='utf-8')))

def ranges(points):
    groups = []
    for point in sorted(points):
        if groups and groups[-1][1] + 1 == point:
            groups[-1][1] = point
        else:
            groups.append([point, point])
    return ','.join(f'U+{a:X}' + (f'-{b:X}' if a != b else '') for a,b in groups)

css = ['/* Generated by scripts/build-fonts.py; retain original OFL licenses. */']
for folder, source, family, prefix in [
    ('source-han-serif', 'SourceHanSerifSC-VF.woff2', 'Site Han Serif', 'serif'),
    ('source-han-sans', 'SourceHanSansSC-VF.woff2', 'Site Han Sans', 'sans'),
]:
    source_path = FONTS / folder / source
    fingerprint = hashlib.sha256(source_path.read_bytes()).hexdigest()
    font = TTFont(source_path)
    points = set(font.getBestCmap())
    font.close()
    latin = sorted(p for p in points if p < 0x300)
    common = [p for p,_ in counts.most_common() if p in points and p not in latin]
    rest = sorted(points - set(latin) - set(common))
    shards = [latin] + [common[i:i+768] for i in range(0,len(common),768)] + [rest[i:i+2048] for i in range(0,len(rest),2048)]
    for index, chars in enumerate(shards):
        filename = f'{prefix}-{index:02}.woff2'
        target = OUT / filename
        stamp = ROOT / 'output/font-sources' / f'{prefix}-{index:02}.sha256'
        if target.exists() and stamp.exists() and stamp.read_text() == fingerprint:
            previous = TTFont(target)
            unchanged = set(previous.getBestCmap()) == set(chars)
            previous.close()
            if unchanged:
                css.append(f'@font-face {{ font-family: "{family}"; font-style: normal; font-weight: 250 900; font-display: swap; src: url("/fonts/web/{filename}") format("woff2"); unicode-range: {ranges(chars)}; }}')
                continue
        font = TTFont(source_path)
        options = subset.Options()
        options.layout_features = ['*']
        options.name_IDs = ['*']
        sub = subset.Subsetter(options=options)
        sub.populate(unicodes=chars)
        sub.subset(font)
        # Use a distinct family name for the derived web subsets.
        for entry in font['name'].names:
            if entry.nameID in (1,3,4,6,16):
                value = family.replace(' ', '') if entry.nameID == 6 else family
                entry.string = value.encode(entry.getEncoding())
        filename = f'{prefix}-{index:02}.woff2'
        font.flavor = 'woff2'
        font.save(OUT / filename)
        font.close()
        stamp.parent.mkdir(parents=True, exist_ok=True)
        stamp.write_text(fingerprint)
        css.append(f'@font-face {{ font-family: "{family}"; font-style: normal; font-weight: 250 900; font-display: swap; src: url("/fonts/web/{filename}") format("woff2"); unicode-range: {ranges(chars)}; }}')
    print(f'{family}: {len(shards)} shards, {len(points)} codepoints', flush=True)
for source, family, style, weight, filename in [
    ('newsreader/Newsreader[opsz,wght].ttf','Newsreader','normal','200 800','newsreader.woff2'),
    ('newsreader/Newsreader-Italic[opsz,wght].ttf','Newsreader','italic','200 800','newsreader-italic.woff2'),
]:
    font=TTFont(FONTS/source)
    font.flavor='woff2'
    font.save(OUT/filename)
    font.close()
    css.append(f'@font-face {{ font-family: "{family}"; font-style: {style}; font-weight: {weight}; font-display: swap; src: url("/fonts/web/{filename}") format("woff2"); }}')
for style, filename in [('normal','MapleMono-VF.woff2'),('italic','MapleMono-Italic-VF.woff2')]:
    css.append(f'@font-face {{ font-family: "Maple Mono"; font-style: {style}; font-weight: 100 800; font-display: swap; src: url("/fonts/maple-mono/{filename}") format("woff2"); }}')
(ROOT/'docs/.vitepress/theme/styles/fonts.css').write_text('\n'.join(css)+'\n',encoding='utf-8')
